/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pack_forms;

import Pack_classes.VALIDACION_TRABAJADORES;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class INICIO_SESION_TRABAJADORES extends javax.swing.JFrame {

    private static Scanner sc;
    private static int NumIntentos;
    private static String user, pass;

    public static void setNumIntentos(int NumIntentos) {
        INICIO_SESION_TRABAJADORES.NumIntentos = NumIntentos;
    }
    
    
    
    /**
     * Creates new form INICIO_SESION_ADMIN
     */
    public INICIO_SESION_TRABAJADORES() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnInicioSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRAB ADMINISTRATIVA");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Password:");

        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("INICIO SESION");

        jLabel4.setText("Cargo:");

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Boleteria", "Confiteria", "Administrativa" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUser)
                                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnInicioSesion)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnInicioSesion)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        frmSTART trab = new frmSTART();
        trab.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        
        FileReader fr = null;
        try {
            // TODO add your handling code here:
            int NumLineas = 0;
            int i = 0;
            String [] usuarios = null;
            String linea;
            
            
            
            
            if(cboCargo.getSelectedIndex() == 1){
                sc = new Scanner(new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresBoleteria.txt"));
                File f = new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresBoleteria.txt");
                
                fr = new FileReader(f);
            
                BufferedReader br = new BufferedReader(fr);
            
                try {
                    while((linea = br.readLine()) != null){
                        NumLineas++;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else if(cboCargo.getSelectedIndex() == 2){
                sc = new Scanner(new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresConfiteria.txt"));
                File f = new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresConfiteria.txt");
                
                fr = new FileReader(f);
            
                BufferedReader br = new BufferedReader(fr);
            
                try {
                    while((linea = br.readLine()) != null){
                        NumLineas++;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }else{
                sc = new Scanner(new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresAdministrativa.txt"));
                File f = new File("D:\\PROYECTO_TECPRO\\src\\Data\\TrabajadoresAdministrativa.txt");
                
                fr = new FileReader(f);
            
                BufferedReader br = new BufferedReader(fr);
            
                try {
                    while((linea = br.readLine()) != null){
                        NumLineas++;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(Level.SEVERE, null, ex);
                }        
                
                                
            }
            
            
            
            
            
            
            
            usuarios = new String [NumLineas]; //tamañño del arreglo
            
            //mientras haya una linea valida, que la agrege al arreglo
            while(sc.hasNextLine()){
                usuarios[i++] = sc.nextLine();  //almacenando cada linea en una posicion del arreglo **en la posicion: i
            }
            
            NumIntentos++;
            
            user = txtUser.getText();
            pass = txtPass.getText();
            
            
            
            
            
            
            
            VALIDACION_TRABAJADORES val = new VALIDACION_TRABAJADORES(); 
            val.ValidadUsuario(usuarios, user, pass, NumIntentos, cboCargo.getSelectedItem().toString());
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(NumIntentos == 0)
            this.dispose();
        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO_SESION_TRABAJADORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO_SESION_TRABAJADORES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
